// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmVMCzHsod4ZQReXyhxNhacPKZufkF1vg',
    appId: '1:229543906854:web:50a49ebdc719c05edda0e7',
    messagingSenderId: '229543906854',
    projectId: 'money-tracker-app-9375b',
    authDomain: 'money-tracker-app-9375b.firebaseapp.com',
    storageBucket: 'money-tracker-app-9375b.firebasestorage.app',
    measurementId: 'G-Q4CYMZCVRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANZAoRw0nDbcSt7tjS8iNFNi1O39znptk',
    appId: '1:229543906854:android:6cb32821f1e7e89adda0e7',
    messagingSenderId: '229543906854',
    projectId: 'money-tracker-app-9375b',
    storageBucket: 'money-tracker-app-9375b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXeeoBiM4qARxmH3jX7Uy08UxfsypK9cE',
    appId: '1:229543906854:ios:aec465421ef3c053dda0e7',
    messagingSenderId: '229543906854',
    projectId: 'money-tracker-app-9375b',
    storageBucket: 'money-tracker-app-9375b.firebasestorage.app',
    iosBundleId: 'com.example.moneyTrackerApp',
  );
}
